### ISSUE TITLE
Task 4.9: Explain changing version for Cert Authority and Recipient

### ISSUE THREAD

**Issue by Anghus** [HoneycuttInc/Warkworth#5]
Exercise 4, Task 9: It would be good to know specifically why the default Windows OS version must be changed for the Certificate Authority and Certificate recipient. It does not seem clear which functionality will break if these configurations do not change or which features we want to enable that require a different OS version.

**Comment by networkingguru** [comment]
Done. FYI, this appears to be task 4.5, not 4.9.
