### ISSUE TITLE
VPN migration lab feedback

### ISSUE THREAD

**Issue by chris-howie** [HoneycuttInc/Warkworth#9]
1,6 - Should we move the network navigation to settings app?
1.8 - (1) Select Use the following DNS server addresses. this is already selected
1.9, 8.2, 8.10, 10.3, 11.1, 15.1 - add "Read knowledge" verbiage
1.10 I would change the knowledge box to the alert so that people see it right away
1.12 Mentions ISE, not PowerShell
1.13 May want to say something like "from the taskbar, open edge" indicating where to open it from
3.4 - I see the customer's point about not using Mark (a domain admin) as the only VPN user. Maybe we should consider using Lori
Exercise 3 has several ">" for multi-select , instead of using "then select"
4.2 Template name should not be plural
7.2, 7.4, 8.3 I don't think we should use the Windows key + R (Could replace with click start and then type the command)
7.2 We may want to explain the sign-out and sign back in
8.3 I would identify the server you are re-logging into 
9.11, 11.4 need to fix the list selection language
11.6 need to break the "Next" into separate actions 
13.1 I would tell the user why they are using the 10.0.1.2 address
15.1 should say ISE
15.3, 15.4 should say PowerShell
16.1, 17.1, 17.14, 18.1, 20.1 missing VM switch
16.4,17.16 knowledge is missing
16.6 add "select enter" after commands
17.2 just a note that the icon for SCCM console is on the taskbar, you may consider having them use that :)
18.5 needs to be two tasks
18.6 we probably should have shown the DA section to them before removing it. They don't have a frame of reference 
19.1 being prompted for updates on servers
19.2 Just call the "far details pane" the "task Pane" or "right-hand task pane" (may ask Michelle her opinion so I don't get my hand slapped)
20.2 Server Manager is already open, no need to tell them to open it

I would consider not doing 18.07 -9 and instead verify connectivity on workstation 1 after the reboot and switching the NICs (like I mentioned in the deployment guide)

Deprovision process needs to be updated per the migration guide. (Check deprovision sequence)

**Comment by networkingguru** [comment]
Chris, most of these are either resolved in the Deployment lab, or will need to be resolved for both labs, so I am going to hit them once feedback for the deployment lab is finished.

**Comment by networkingguru** [comment]
1.6 - We discussed this in an email with Jerry and decided to continue using the Network and Sharing center
3.4 - I would rather not use Lori, as doing so requires a large number of changes to both labs which then must be tested (I have to create the account in VM's, then in the migration lab make it a member of the allowed users for direct access, then change instances where the Mark account is reference throughout the text for VPN login to Lori, etc.) . Instead, I added a knowledge item explaining that domain admin membership is not required and any account can be used. If this is not acceptable please let me know and I will rewrite both labs to support the Lori account instead. 
4.2 - Sorry, I'm not understanding the issue? See screenshots below:
![image](https://user-images.githubusercontent.com/4753203/34314504-d5752a44-e739-11e7-8396-b5cd3799988d.png)
![image](https://user-images.githubusercontent.com/4753203/34314511-e40742fe-e739-11e7-92a9-51210e0e8f8a.png)
9.11, 11.4 - I believe this has been corrected, but please let me know if this terminology is incorrect.
I believe all the rest of the settings, except for the deprovisioning update, are correct in both labs now.
